# -*- shell-script -*-
# If not running interactively, then don't do anything
[ -z "$PS1" ] && return

############# stuff lifted from .default_bashrc #################

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

############# returning to stuff terran wrote ###############

# First, configure environment variables and other system-specific
# functionality (if it hasn't previously been executed)
inittop="${HOME}/.init/sh/getenv"
if [ -f "${inittop}" ]; then
    . "${inittop}"
fi
