#!/bin/csh -f

# Copyright Terran Lane 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2012

umask 077
if ( ! -d /tmp/${USER}/netscape/cache ) then
  mkdir -p /tmp/${USER}/netscape/cache
endif
foreach i (0 1 2)
  if ( ! -d /tmp/${USER}/scratch${i} ) then
    mkdir -p /tmp/${USER}/scratch${i}
  endif
end
