#!/bin/csh -f

mesg n

# be paranoid about the !%&@$#%#$% quota system...
if (`quota -v | grep -ic EXPIRED`) then
  /usr/bin/echo "\a\a\a"
  echo 'Whoa boss...  Looks like they caught up with you.'
  echo 'better ditch the goods.  Fast.'
endif

# term handling stuff

# Termcap style.  Antiquated?
# set termcapfile=${HOME}/.init/term/termcap.${TERM}
# if (-r ${termcapfile} ) then
#   setenv TERMCAP `cat ${termcapfile}`
# endif

# Terminfo style
set terminfodir=${HOME}/.init/terminfo/
if ( `grep -c ${TERM} ${terminfodir}/termlist` ) then
  setenv TERMINFO ${terminfodir}
endif

set termspecfile=${HOME}/.init/termspec/termspec.${TERM}
if ( -r ${termspecfile} ) then
  source ${termspecfile}
endif

if ( ! $?skip_tset ) then
  set noglob
  eval `tset -s -Q`
  unset noglob
endif

# now init term settings to the "right thing" (TM)
#stty erase ^H
stty intr ^C

unset termcapfile
unset terminfodir
unset termspecfile
unset skip_tset

# biff y 
mesg y
newmail
uptime
mailp
